import uuid
from pathlib import Path
from typing import BinaryIO, Protocol


class StoragePort(Protocol):
    """Abstracts where bytes live, so LocalFileSystemStorage can be swapped for
    an S3/MinIO adapter later without touching any call site (§5.3, §20)."""

    def save_temp(self, stream: BinaryIO) -> Path: ...

    def build_storage_path(self, document_id: uuid.UUID, version_number: int, filename: str) -> str: ...

    def commit(self, temp_path: Path, storage_path: str) -> None: ...

    def discard(self, temp_path: Path) -> None: ...

    def copy(self, source_storage_path: str, dest_storage_path: str) -> None: ...

    def open_for_read(self, storage_path: str) -> BinaryIO: ...

    def delete(self, storage_path: str) -> None: ...
