"""add organization settings columns

Phase 1 of Organization Settings: AI Suggestions on/off, Duplicate Detection
on/off, and a total storage limit in MB (every byte on disk for the
organization — superseded versions and trashed documents included — not a
per-file cap; that stays settings.max_upload_size_mb).

Every column is NOT NULL with a server_default, so the three organizations
that already exist are backfilled by this ALTER itself. No second migration,
no backfill script, and no window where a row has no settings — unlike the
organization_id migrations (7bbf96ca24d8 -> 8ebd25762f70), which needed the
nullable-then-enforce dance only because there was no sensible default value
to give existing rows.

Safe against the older deployed code: adding a column with a default doesn't
break inserts that omit it. The usual ordering hazard for this project (one
database serving local and production) is therefore the revision-not-found
crash on restart, not data loss — see the warning at the top of
PROJECT_STATUS.md.

Revision ID: 2a25f628ba2e
Revises: a3b7efaeff2c
Create Date: 2026-07-30 21:37:16.168035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a25f628ba2e'
down_revision: Union[str, Sequence[str], None] = 'a3b7efaeff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('ai_suggestions_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('organizations', sa.Column('duplicate_detection_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('organizations', sa.Column('storage_limit_mb', sa.Integer(), server_default='150', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'storage_limit_mb')
    op.drop_column('organizations', 'duplicate_detection_enabled')
    op.drop_column('organizations', 'ai_suggestions_enabled')
    # ### end Alembic commands ###
