"""add ai_document_analysis table and generate_metadata job type

Revision ID: 61938a14933d
Revises: a8e785ca1e16
Create Date: 2026-07-24 11:52:31.741703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61938a14933d'
down_revision: Union[str, Sequence[str], None] = 'a8e785ca1e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Note: autogenerate again flagged ux_categories_name_lower, ix_documents_active_updated_at,
# and ix_documents_search_vector as "removed" — the same pre-existing false positive documented
# in a8e785ca1e16 and e97f9d207d17 (hand-added via op.execute()/postgresql_using, invisible to
# the ORM's Index() metadata). Stripped from both upgrade() and downgrade() below.
#
# Autogenerate also does not detect new members added to an existing Postgres enum type (it only
# diffs column/table structure), so the AiJobType.GENERATE_METADATA addition is hand-written below
# as ALTER TYPE ... ADD VALUE, not something autogenerate produced.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ai_job_type ADD VALUE IF NOT EXISTS 'GENERATE_METADATA'")
    op.create_table('ai_document_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ai_analysis_status'), server_default='PENDING', nullable=False),
    sa.Column('suggested_title', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(), nullable=True),
    sa.Column('suggested_description', sa.Text(), nullable=True),
    sa.Column('suggested_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('suggested_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('input_char_count', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_document_analysis_document_version_id'), 'ai_document_analysis', ['document_version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_document_analysis_document_version_id'), table_name='ai_document_analysis')
    op.drop_table('ai_document_analysis')
    # Postgres doesn't support removing a value from an existing enum type
    # (short of recreating the type entirely); GENERATE_METADATA is left in
    # ai_job_type on downgrade, same tradeoff as any other additive enum value.
    # ### end Alembic commands ###
