"""add document_extracted_text and ai_jobs tables

Revision ID: a8e785ca1e16
Revises: e97f9d207d17
Create Date: 2026-07-24 00:52:56.059275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e785ca1e16'
down_revision: Union[str, Sequence[str], None] = 'e97f9d207d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Note: autogenerate also flagged ux_categories_name_lower, ix_documents_active_updated_at,
# and ix_documents_search_vector as "removed" — the same noise documented in
# e97f9d207d17. Those three are hand-added via op.execute()/postgresql_using in the initial
# migration and aren't in the ORM's Index() metadata, so autogenerate can't see they still
# exist. Stripped from both upgrade() and downgrade() below; only the two new tables are real.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('EXTRACT', name='ai_job_type'), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', name='ai_job_status'), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_document_version_id'), 'ai_jobs', ['document_version_id'], unique=False)
    op.create_index('ix_ai_jobs_status_next_retry_at', 'ai_jobs', ['status', 'next_retry_at'], unique=False)
    op.create_table('document_extracted_text',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text_path', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('PDF', 'DOCX', 'XLSX', 'PPTX', 'PLAIN', name='extraction_method'), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'UNSUPPORTED', name='extraction_status'), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extracted_text_document_version_id'), 'document_extracted_text', ['document_version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extracted_text_document_version_id'), table_name='document_extracted_text')
    op.drop_table('document_extracted_text')
    op.drop_index('ix_ai_jobs_status_next_retry_at', table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_document_version_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
