"""add SHARED activity event type

Revision ID: b7c1e4a9d520
Revises: acd53d2f12ab
Create Date: 2026-07-27 22:20:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b7c1e4a9d520'
down_revision: Union[str, Sequence[str], None] = 'acd53d2f12ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated: Alembic does not detect new members added to an existing
# Postgres enum type (it only diffs table/column structure) — the same reason GENERATE_METADATA
# (61938a14933d) and GENERATE_EMBEDDING (ce5e3e5c56bd) needed hand-written ALTER TYPE statements.
#
# Kept as its own revision rather than folded into acd53d2f12ab because that one is already
# applied; amending an applied migration would leave this environment and a fresh one with
# different histories.


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'SHARED'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no way to remove a value from an existing enum type short of recreating it,
    # so SHARED is left in place on downgrade — the same accepted tradeoff as every other
    # additive enum value in this project.
    pass
