"""add document_vector_embeddings table and generate_embedding job type

Revision ID: ce5e3e5c56bd
Revises: 61938a14933d
Create Date: 2026-07-25 00:16:30.275171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

# revision identifiers, used by Alembic.
revision: str = 'ce5e3e5c56bd'
down_revision: Union[str, Sequence[str], None] = '61938a14933d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Note: autogenerate again flagged ux_categories_name_lower, ix_documents_active_updated_at,
# and ix_documents_search_vector as "removed" — the same pre-existing false positive documented
# in a8e785ca1e16, e97f9d207d17, and 61938a14933d (hand-added via op.execute()/postgresql_using,
# invisible to the ORM's Index() metadata). Stripped from both upgrade() and downgrade() below.
#
# Autogenerate also does not detect new members added to an existing Postgres enum type, and has
# no way to know pgvector's `vector` type needs its extension enabled first — both hand-written
# below (ALTER TYPE ... ADD VALUE, CREATE EXTENSION), same pattern as 61938a14933d.
#
# Similar Document Detection track (Phase 2 of the AI roadmap): document_vector_embeddings is kept
# fully separate from ai_document_analysis — different shape (a 768-dim vector queried via pgvector
# ANN search), same 1:1-per-document_version relationship and job-observability columns.


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("ALTER TYPE ai_job_type ADD VALUE IF NOT EXISTS 'GENERATE_EMBEDDING'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_vector_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', PGEnum('PENDING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='ai_analysis_status', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('input_char_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_vector_embeddings_document_version_id'), 'document_vector_embeddings', ['document_version_id'], unique=True)
    # ### end Alembic commands ###

    # HNSW index for cosine-distance ANN search (SimilarityService/embedding <=> query) —
    # standard pgvector index, no training/list-count step needed (unlike ivfflat).
    op.execute(
        "CREATE INDEX ix_document_vector_embeddings_embedding_hnsw "
        "ON document_vector_embeddings USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_document_vector_embeddings_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_vector_embeddings_document_version_id'), table_name='document_vector_embeddings')
    op.drop_table('document_vector_embeddings')
    # ### end Alembic commands ###

    # Postgres doesn't support removing a value from an existing enum type
    # (short of recreating the type entirely); GENERATE_EMBEDDING is left in
    # ai_job_type on downgrade, same tradeoff as GENERATE_METADATA's own
    # migration (61938a14933d). The vector extension is also left installed
    # on downgrade — dropping it is a separate, deliberate operational
    # decision, not something a schema downgrade should do implicitly.
